Fix for #484: module 'plistlib' has no attribute 'readPlist' (#485)
* Fix for #484: module 'plistlib' has no attribute 'readPlist'

Pythonista 3 was recently upgraded to python3.10. This fix mirigates plist.py:8: DeprecationWarning: The readPlist function is deprecated, use load() instead pl=plistlib.readPlist(fileName)

* Typo fix

* isAlive(

* Fix whitespace

---------

Co-authored-by: Christian Clauss <cclauss@me.com>